remote_theme: lewismiddleton/cayman-dark
title: Welcome to my website
description: :)
show_downloads: false
google_analytics:
gems:
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
- jekyll-youtube
- jekyll-giphy
- jekyll-umlauts
